# Generated by Django 5.0 on 2023-12-15 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_rename_post_comment_post_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post_id",
            new_name="post",
        ),
    ]
