# Generated by Django 4.1.13 on 2023-12-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_alter_studypost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="studypost",
            name="likesCount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
