# Generated by Django 4.1.13 on 2023-12-18 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0003_studypost_likescount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studylike',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studylike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studypost'),
        ),
        migrations.AlterField(
            model_name='studylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studylike',
            unique_together={('user', 'post')},
        ),
    ]
