# Generated by Django 4.1.13 on 2023-12-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_name_alter_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="학년"),
        ),
    ]
